### ISSUE TITLE
AttributeError on library using IAM

### ISSUE THREAD

**Issue by BinarSkugga** [googleapis/python-iam#185]
Hi, we've been having trouble installing and using various Google Cloud libraries recently. This error pops up:
```
Traceback (most recent call last):
  File "C:/Users/_/Documents/git-sollum/sollumcloudplatform/src/main.py", line 27, in <module>
    from src.procedures import create_app
  File "C:\Users\_\Documents\git-sollum\sollumcloudplatform\src\procedures.py", line 17, in <module>
    from src.utils.decorators import memoize
  File "C:\Users\_\Documents\git-sollum\sollumcloudplatform\src\utils\decorators.py", line 16, in <module>
    from google.cloud.pubsub_v1.subscriber.message import Message
  File "C:\Users\_\Documents\git-sollum\sollumcloudplatform\venv\lib\site-packages\google\cloud\pubsub_v1\__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1 import types
  File "C:\Users\_\Documents\git-sollum\sollumcloudplatform\venv\lib\site-packages\google\cloud\pubsub_v1\types.py", line 22, in <module>
    from google.iam.v1 import iam_policy_pb2
  File "C:\Users\_\Documents\git-sollum\sollumcloudplatform\venv\lib\site-packages\google\iam\v1\iam_policy_pb2.py", line 35, in <module>
    from google.iam.v1 import options_pb2 as google_dot_iam_dot_v1_dot_options__pb2
  File "C:\Users\_\Documents\git-sollum\sollumcloudplatform\venv\lib\site-packages\google\iam\v1\options_pb2.py", line 36, in <module>
    _GETPOLICYOPTIONS = DESCRIPTOR.message_types_by_name["GetPolicyOptions"]
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
```

It happens on both linux and windows. Here's our versions:
google-api-core==1.30.0
google-cloud-datastore==2.1.3
google-cloud-pubsub==2.6.0
google-cloud-iot==2.1.0
google-cloud-kms==2.3.0
google-cloud-error-reporting==1.1.0
google-cloud-tasks==2.3.0
google-cloud-scheduler==2.1.0
google-cloud-storage==1.39.0

**Comment by BinarSkugga** [comment]
This is issue has also been posted on StackOverflow 11 days ago: https://stackoverflow.com/questions/71825406/pip-install-google-cloud-logging-failed-in-docker

**Comment by BinarSkugga** [comment]
Upgrading to protobuf version 3.20.1 fixed this issue. Should probably be pinned on the requirements here.
